version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:123@db:3306/user_database

  db:
    image: mariadb:11.6  # Используем конкретную версию MariaDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: user_database
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
