version: 1
services:
  - type: web
    name: MyFastAPIService
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true