version: 1
services:
  - type: web
    name: MyFastAPIService
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn dist.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      DATABASE_URL: your_database_url_here
